### ISSUE TITLE
The default setSpec is missing from the OAI Record Header

### ISSUE THREAD

**Issue by phochste** [ugent-library/oai-service#9]
The setSpec `biblio` contains all Biblio records but is missing in the OAI Record Headers. E.g.

https://oai.libdev.ugent.be/?verb=GetRecord&metadataPrefix=oai_dc&identifier=01H2WKEADERP92QFR96PBZ0SP1

**Comment by phochste** [comment]
This setSpec also contains no records:

https://oai.libdev.ugent.be/?verb=ListIdentifiers&metadataPrefix=oai_dc&set=biblio

**Comment by nics** [comment]
@ phochste fixed and will deploy later today, but note that the spec says:
```
The set hierarchy of a repository may include sets that are empty.
```
